### ISSUE TITLE
Needs Update to 1.10

### ISSUE THREAD

**Issue by NewgroundGaming** [JoelGodOfwar/NoEndermanGrief#1]
Could you update this and dragon drop elytra to 1.10 and update them on the websites. These 3 plugins are what we were trying to do with command blocks but We have no clue if they'll work.

**Comment by JoelGodOfwar** [comment]
Dragon Drop Elytra will be updated in a few minutes. NoEndermanGrief does not need an update as it works in 1.10

**Comment by NewgroundGaming** [comment]
Just checked the bukkit dev webpage for the dragon drop elytra plugin. I don't see an update on there yet.

**Comment by JoelGodOfwar** [comment]
They seem to be taking a while to approve the file. Try downloading it from
spigotmc
https://www.spigotmc.org/resources/dragondropelytra.22803/

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-a
Virus-free.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2322-a
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
