### ISSUE TITLE
Questions about Plugin functionality - Finding Enderman with blocks in hand after installing

### ISSUE THREAD

**Issue by MCHalfAssed** [JoelGodOfwar/NoEndermanGrief#4]
Hello! 

I noticed that I'm still finding Enderman in my server with blocks in their hand. It's possible that they existed before I installed the plugin, so I came here to ask two questions:

If there were Enderman in my server that already had blocks in their hand, will the plugin remove them?

Also - Does the plugin remove Endermans ability to pickup/place blocks completely, or only disables placing blocks?

I mostly installed this plugin because Enderman with blocks were not despawning and piling up in caves, to provide some insight on why I installed it.

**Comment by JoelGodOfwar** [comment]
The plugin cancels the event of the Enderman picking up a block.
